# Generated by Django 3.0.3 on 2020-08-14 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='organisation.Rack'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='desc_units',
            field=models.BooleanField(help_text='По умолчанию нумерация юнитов снизу вверх', verbose_name='Top to buttom'),
        ),
    ]
