# Generated by Django 3.0.3 on 2020-03-01 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('name', 'pk')},
        ),
        migrations.AlterModelOptions(
            name='devicerole',
            options={'ordering': ['name']},
        ),
    ]
