# Generated by Django 3.0.3 on 2020-08-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_auto_20200815_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='desc_units',
            field=models.BooleanField(default=False, help_text='По умолчанию нумерация юнитов снизу вверх', verbose_name='Top to buttom'),
        ),
    ]
