# Generated by Django 3.0.3 on 2020-08-02 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_auto_20200802_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='version',
        ),
    ]
