# Generated by Django 3.0.3 on 2020-08-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_auto_20200815_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='desc_units',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Сверху вниз'), (1, 'Снизу вверх')], default=1, help_text='По умолчанию нумерация юнитов снизу вверх', verbose_name='Top to buttom'),
        ),
    ]
