# Generated by Django 3.0.3 on 2020-08-19 11:26

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('extend', '0003_auto_20200817_0157'),
        ('organisation', '0006_auto_20200815_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='extend.TaggedItem', to='extend.Tag', verbose_name='Tags'),
        ),
    ]
