# Generated by Django 3.0.3 on 2020-08-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0006_auto_20200806_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendormodel',
            name='depth',
            field=models.BooleanField(default=True, help_text='Default is Full Depth', verbose_name='Full Depth'),
        ),
        migrations.AlterField(
            model_name='vendormodel',
            name='u_height',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Height (U)'),
        ),
    ]
