# Generated by Django 3.0.3 on 2020-09-11 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0007_location_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='face_position',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Located at the front of rack'), (0, 'Located at the rear of rack')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Unit Number device starts location in the rack', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Unit Number'),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial',
            field=models.CharField(blank=True, max_length=50, verbose_name='Serial number'),
        ),
        migrations.AlterField(
            model_name='vendormodel',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
