# Generated by Django 3.0.3 on 2020-08-16 22:50

from django.db import migrations, models
import extend.forms


class Migration(migrations.Migration):

    dependencies = [
        ('extend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='date',
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=extend.forms.ColorField(default='9e9e9e', max_length=6),
        ),
        migrations.AddField(
            model_name='tag',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
