# Generated by Django 3.0.3 on 2020-08-16 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extend', '0002_auto_20200817_0150'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='taggeditem',
            index_together=set(),
        ),
    ]
