# Generated by Django 3.0.3 on 2020-08-27 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extend', '0004_auto_20200827_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggeditem',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extend_taggeditem_items', to='extend.Tag'),
        ),
    ]
